# Generated by Django 2.0.6 on 2018-06-19 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 6, 19, 17, 49, 35, 138785))),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=20)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_username', models.CharField(max_length=20)),
                ('registration_date', models.DateTimeField(default=datetime.datetime(2018, 6, 19, 17, 49, 35, 138785))),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 6, 19, 17, 49, 35, 139785))),
                ('last_answer_date', models.DateTimeField(default=datetime.datetime(2018, 6, 19, 17, 49, 35, 139785))),
                ('answers', models.ManyToManyField(to='forum.Answer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='forum.CustomUser')),
                ('last_answer_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_answer_author', to='forum.CustomUser')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='topics',
            field=models.ManyToManyField(to='forum.Topic'),
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.CustomUser'),
        ),
    ]
