# Generated by Django 2.0.6 on 2018-06-19 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='last_answer_author',
        ),
        migrations.AddField(
            model_name='topic',
            name='answers_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='visits_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 18, 6, 36, 312991)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 18, 6, 36, 311990)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 18, 6, 36, 313990)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_answer_date',
            field=models.DateTimeField(default=''),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
