# Generated by Django 2.0.6 on 2018-06-19 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180619_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 18, 20, 27, 579617)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 18, 20, 27, 578618)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 18, 20, 27, 579617)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_answer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
