# Generated by Django 2.0.6 on 2018-06-20 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20180619_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 13, 13, 20, 79986)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 13, 13, 20, 79986)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 13, 13, 20, 80985)),
        ),
    ]
